export ROOT_DIR=$(pwd)
export BUILD_DIR=${ROOT_DIR}/Builds
export SCRIPT_DIR=${ROOT_DIR}/scripts
export Qemu_x86=$(which qemu-system-x86_64)
export cpus=$(( $(nproc) / 2 ))
export mem="2048"
export Linux_Version="linux-5.15.31"
export Lin_Path=${BUILD_DIR}/${Linux_Version}
export GDB=$(which gdb)
export ubu_iso=${BUILD_DIR}/ubuntu-20.04.4-live-server-amd64.iso
export disk_image=${BUILD_DIR}/drive1.qcow2
export ramfs=${BUILD_DIR}/ramdisk.img
export rootfs=${BUILD_DIR}/root-filesystem-x86_64
export rootdisk=${BUILD_DIR}/disk1.img
export machine_image=${BUILD_DIR}/system-image-x86_64
